package com.example.kotlin_materialdesign_nasa.recycler.mViewHolders

import android.view.View
import androidx.recyclerview.widget.RecyclerView
import com.example.kotlin_materialdesign_nasa.databinding.FragmentRecyclerEarthBinding
import com.example.kotlin_materialdesign_nasa.recycler.Data
import com.example.kotlin_materialdesign_nasa.recycler.OnListItemClickListener
import com.example.kotlin_materialdesign_nasa.recycler.RecyclerViewAdapter
import com.example.kotlin_materialdesign_nasa.utils.EARTH_R
import com.example.kotlin_materialdesign_nasa.utils.HEADER_R
import com.example.kotlin_materialdesign_nasa.utils.MARS_R
import okhttp3.internal.notify

